39 make robot drive to goal to deliver balls
MikaelFangel/GolfBot pull request #116
Opened 2023-06-15 11:38 UTC by yech199

Routine for delivering ball to goal. Some offsets might be off and should be corrected, but this is a general issue :sweat_smile:

2023-06-15 12:17 UTC, Greve2001 requested changes
I have commented the code you have made. I have not commented on the parts from Mikael's branch, as that needs to be merged first

2023-06-15 12:17 UTC, Greve2001 commented on remote/src/main/java/courseObjects/Border.java
> +        if (this.smallGoalPos == null)
I think a better name for this, would be "direction"

2023-06-15 12:17 UTC, Greve2001 commented on remote/src/main/java/courseObjects/Border.java
> +        int offset = 25;
Should this not change, depending on the robots length?

2023-06-15 12:17 UTC, Greve2001 commented on remote/src/main/java/vision/Algorithms.java
> +    }
Should we not just remove this wrapper, and just call the inner method, the other places

2023-06-16 07:13 UTC, MikaelFangel approved these changes

2023-06-16 07:52 UTC, MikaelFangel approved these changes

2023-06-16 07:54 UTC, merged