96 correct object position using height
MikaelFangel/GolfBot pull request #97
Opened 2023-06-09 12:25 UTC by Greve2001

2023-06-09 13:55 UTC, yech199 requested changes

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/courseObjects/Course.java
> +        return border;
```suggestion
        return this.border;
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/courseObjects/Course.java
> +        return balls;
```suggestion
        return this.balls;
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/courseObjects/Course.java
> +        return robot;
```suggestion
        return this.robot;
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/courseObjects/Course.java
> +        return cameraHeight;
```suggestion
        return this.cameraHeight;
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/courseObjects/Course.java
> +        return cameraPosition;
```suggestion
        return this.cameraPosition;
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/courseObjects/Course.java
> +    private final int ResolutionHeight = 768;
Variables should start with small letter

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/courseObjects/Course.java
> +        return ResolutionHeight;
```suggestion
        return this.resolutionHeight;
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/courseObjects/Course.java
> +        return resolutionWidth;
```suggestion
        return this.resolutionWidth;
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/vision/Algorithms.java
> +import courseObjects.Course;
```suggestion
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/vision/DetectionController.java
>  import courseObjects.Robot;
```suggestion
import courseObjects.*;
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/vision/DetectionController.java
> +                correctedFront.x, correctedFront.y);
Not used

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/vision/detection/BorderDetector.java
> +        cameraOffset = new Point(offsetX, offsetY);
```suggestion
        this.cameraOffset = new Point(offsetX, offsetY);
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/vision/detection/BorderDetector.java
> +        return this.cameraOffset;
```suggestion
    public Border getBorder() {
        return this.border;
    }
    
    public Point getCameraOffset() {
        return this.cameraOffset;
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/vision/math/Geometry.java
> +     * @param distanceToCamera distance from object to camera, in a perpendicular line to the camera.
Parameters in cm

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/vision/math/Geometry.java
> +        double largeTriangleHypotenuse = Math.sqrt(Math.pow(heightCamera,2)+Math.pow(distanceToCamera,2));
```suggestion
        double largeTriangleHypotenuse = Math.sqrt(Math.pow(heightCamera, 2) + Math.pow(distanceToCamera, 2));
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/vision/math/Geometry.java
> +        double angelHeight = Math.toDegrees(Math.asin(heightCamera/largeTriangleHypotenuse));
```suggestion
        double angelHeight = Math.toDegrees(Math.asin(heightCamera / largeTriangleHypotenuse));
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/vision/math/Geometry.java
> +                (heightObject*Math.sin(Math.toRadians(smallTriangleGroundAngel)))/Math.sin(Math.toRadians(angelHeight));
```suggestion
                (heightObject*Math.sin(Math.toRadians(smallTriangleGroundAngel))) / Math.sin(Math.toRadians(angelHeight));
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/main/java/vision/math/Geometry.java
> +        return distanceToCamera-smallTriangleLength;
```suggestion
        return distanceToCamera - smallTriangleLength;
```

2023-06-09 13:55 UTC, yech199 commented on remote/src/test/java/AlgorithmsTest.java
> +        System.out.println(newPoint.toString());
What is being tested? Can it be tested with assertEquals, so we don't need to manually check the printed value

2023-06-09 13:55 UTC, yech199 commented on remote/src/test/java/AlgorithmsTest.java
> +        System.out.println(newPoint.toString());
What is being tested? Can it be tested with assertEquals, so we don't need to manually check the printed value

2023-06-09 15:02 UTC, Greve2001 reviewed
I have changed everything that i can make sense of

2023-06-10 08:32 UTC, yech199 approved these changes

2023-06-10 08:32 UTC, merged